# Generated by Django 4.0.6 on 2022-11-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_hospital_requests_hospitalrequests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='donor_id',
            field=models.CharField(default='D00000', max_length=10),
        ),
    ]
