# Generated by Django 4.0.6 on 2022-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_donors_donor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_id',
            field=models.CharField(default='P-00', max_length=10),
        ),
    ]
