# Generated by Django 4.0.6 on 2022-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_patients_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.AlterField(
            model_name='hospitalrequests',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
