# Generated by Django 4.1.3 on 2022-12-02 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_delete_patients_alter_hospitalrequests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_units', models.IntegerField()),
                ('hospital_id', models.IntegerField()),
                ('request_id', models.IntegerField()),
                ('blood_type', models.CharField(max_length=10)),
                ('drone_number', models.CharField(max_length=10)),
                ('departure_date', models.CharField(default=datetime.date(2022, 12, 2), max_length=10)),
                ('departure_time', models.CharField(max_length=10)),
                ('expected_time', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'blood_distribution',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='P-00', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('body_weight', models.IntegerField()),
                ('phone_number', models.CharField(max_length=50)),
                ('blood_type', models.CharField(max_length=5)),
                ('blood_quantity', models.IntegerField()),
                ('hospital', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
