# Generated by Django 4.1.3 on 2022-12-01 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_blooddistribution_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddistribution',
            name='departure_date',
            field=models.CharField(default=datetime.date(2022, 12, 1), max_length=10),
        ),
    ]
