# Generated by Django 4.1.3 on 2022-12-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_blooddistribution_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDistribution',
            new_name='HospitalBloodDistribution',
        ),
        migrations.AlterModelTable(
            name='hospitalblooddistribution',
            table='hospital_blood_distribution',
        ),
    ]
