# Generated by Django 4.1.3 on 2022-12-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_rename_blooddistribution_hospitalblooddistribution_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalBloodDistribution',
            new_name='BloodDistribution',
        ),
        migrations.AlterModelTable(
            name='blooddistribution',
            table='blood_distribution',
        ),
    ]
