# Generated by Django 4.1.3 on 2022-12-01 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_blooddistribution_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddistribution',
            name='departure_date',
            field=models.CharField(default=datetime.date(2022, 12, 2), max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddistribution',
            name='drone_number',
            field=models.CharField(max_length=10),
        ),
    ]
